Conflict `nvidia-utils` with `libglvnd`
Reason:

    error: failed to commit transaction (conflicting files)
    /usr/lib/nvidia/libEGL.so exists in both 'libglvnd' and 'nvidia-utils'
    /usr/lib/nvidia/libEGL.so.1 exists in both 'libglvnd' and 'nvidia-utils'